name: Compile .typ Files

on:
    push:
        branches:
            - main
            - feature/test-action

jobs:
    compile-and-commit:
        runs-on: ubuntu-latest

        steps:
            #Checkout the repository
            - name: Checkout source repository
              uses: actions/checkout@v4

            - uses: typst-community/setup-typst@v4

            #Compile the .typ file(s) while preserving folder structure
            - name: Compile .typ files
              run: |
                  mkdir -p compiled
                  find documents -name "*.typ" | while read file; do
                      if [[ "$file" != *"Lettera di Presentazione.typ"* ]]; then
                          output_dir="compiled/$(dirname "$file")"
                          mkdir -p "$output_dir"
                          typst compile --root=/ "$file" "$output_dir/$(basename "${file%.typ}.pdf")"
                      fi
                  done

            # Commit the compiled files to the repository
            - name: Commit compiled files
              run: |
                git config --global user.name "GitHub Actions"
                git config --global user.email "actions@github.com"
                mkdir -p documents_compiled
                cp -r compiled/* documents_compiled/
                git add documents_compiled
                git commit -m "Add compiled .typ files"
                git push