name: Compile

on:
    push:
        branches:
            - main
            - feature/test-action #TODO: remove this line when the action is working

jobs:
    compile:
        runs-on: ubuntu-latest

        steps:
            #Checkout the repository
            - name: Checkout source repository
              uses: actions/checkout@v4

            - uses: typst-community/setup-typst@v4

            #Compile the .typ file(s) while preserving folder structure
            - name: Compile .typ files
              run: |
                  mkdir -p compiled
                  find documents -name "*.typ" | while read file; do
                      if [[ "$file" != *"Lettera di Presentazione.typ"* ]]; then
                          output_dir="compiled/$(dirname "$file")"
                          mkdir -p "$output_dir"
                          typst compile --root=/ "$file" "$output_dir/$(basename "${file%.typ}.pdf")"
                      fi
                  done
                  echo "Compiled files:"
                  find compiled -type f

            # Create folder and copy compiled files
            - name: Create folder and copy compiled files
              run: |
               mkdir -p documents_compiled
               cp -r compiled/documents/* documents_compiled/

            # Commit the compiled files to the repository
            - name: Commit compiled files
              run: |
               git config --global user.name "github-actions[bot]"
               git config --global user.email "github-actions[bot]@users.noreply.github.com"
               git add documents_compiled
               git status
               git commit -m "Add compiled .typ files"
               git push origin feature/test-action