name: Compile and Upload Typst Files

on:
    push:
        branches:
            - feature/SCRUM-87-Automazione-versionamento
    pull_request:
        branches:
            - feature/SCRUM-87-Automazione-versionamento

#TODO: Togliere feature e mettere main prima di fare il merge e togliere la rule relativa al push su github pages

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
    compile:
        runs-on: ubuntu-latest

        steps:
            #Checkout the repository
            - name: Checkout source repository
              uses: actions/checkout@v4

            - uses: typst-community/setup-typst@v4

            - name: Configurazione di Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'

            - name: Converte i file .typ in .pdf
              id: compila_file_typ
              run: python .github/workflows/scripts/compila_file_typ.py

            - name: List files in the repository
              run: ls -R

            # Create an artifact with the compiled files
            - name: Upload compiled files as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: compiled-typst-files
                  path: compiled/

    upload:
        needs: compile
        runs-on: ubuntu-latest
        environment:
         name: github-pages
         url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Clean up old files in GitHub Pages
              run: |
                  git rm -r --cached --ignore-unmatch * || true
                  git clean -fdx || true
                  git commit -m "Clean up old files" || true

            - name: Download compiled files artifact
              uses: actions/download-artifact@v4
              with:
                  name: compiled-typst-files
                  path: documents_compiled/

            - name: Restore Timestamps
              uses: chetan/git-restore-mtime-action@v2

            - name: Generate Directory Listings
              uses: jayanta525/github-pages-directory-listing@main
              with:
                  FOLDER: documents_compiled
              env:
                  TZ: Europe/Rome

            - name: Upload Artifact for Pages
              uses: actions/upload-pages-artifact@v3
              with:
                  name: pages
                  path: documents_compiled/

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
              with:
                  artifact_name: pages