name: Upload to GitHub Pages

on:
  workflow_run:
    workflows: ["Compile typst Files"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Echo test
        run: echo "This is a test"