name: Compile and Commit .typ Files

on:
    push:
        branches:
            - main
            - feature/test-action

jobs:
    compile-and-commit:
        runs-on: ubuntu-latest

        steps:
            #Checkout the repository
            - name: Checkout source repository
              uses: actions/checkout@v4

            - uses: typst-community/setup-typst@v4

            #Compile the .typ file(s) while preserving folder structure
            - name: Compile .typ files
              run: |
                  mkdir -p compiled
                  find documents -name "*.typ" | while read file; do
                      if [[ "$file" != *"Lettera di Presentazione.typ"* ]]; then
                          output_dir="compiled/$(dirname "$file")"
                          mkdir -p "$output_dir"
                          typst compile --root=/ "$file" "$output_dir/$(basename "${file%.typ}.pdf")"
                      fi
                  done

            - name: Generate directory listing
              uses: jayanta525/github-pages-directory-listing@main
              with:
                FOLDER: compiled
              env:
                TZ: Europe/Rome
    
            - name: Upload artifact for GitHub Pages
              uses: actions/upload-pages-artifact@v3
              with:
                path: compiled/
    
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
